---
- name: Prepare check
  ansible.builtin.meta: end_play
  when: (prepare is defined) and (prepare|bool is false)

- name: Update and upgrade the machine
  ansible.builtin.apt:
    upgrade: dist
    update_cache: true

- name: Install node_exporter
  ansible.builtin.import_tasks: node_exporter.yml
  when: node_exporter|bool

- name: Install promtail
  ansible.builtin.import_tasks: promtail.yml
  when: promtail|bool

- name: Firewall setup
  when: firewall_restrict is defined
  ansible.builtin.import_tasks: firewall.yml

- name: Install cosmos software
  ansible.builtin.import_tasks: cosmos_software.yml
  when: cosmos_software|default(true)|bool
