---
default_language_version:
    python: python3.11

default_stages: [commit, push]

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: 3298dda
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: detect-private-key
    - repo: https://github.com/ansible/ansible-lint.git
      rev: v6.18.0
      hooks:
          - id: ansible-lint
            args: ["--exclude", "examples"]
            files: ^ansible/.*\.(yaml|yml)$
            name: Ansible Lint
            description: Run configurations on .ansible-lint file
            verbose: true

    - repo: local
      hooks:
          - id: auto-doc-generator
            name: Auto Documentation Generator
            entry: scripts/auto-doc-generator.sh
            files: ^roles/.*\.ya?ml$
            language: system


    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.5.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
