---
- name: Download binary
  ansible.builtin.get_url:
    url: '{{ binary }}'
    dest: /tmp/binary.tar.gz
    mode: '0700'
    force: yes

- name: Unarchive binary file
  ansible.builtin.unarchive:
    src: /tmp/binary.tar.gz
    dest: /tmp/
    mode: '0755'
    remote_src: true

- name: Copy binary
  ansible.builtin.copy:
    remote_src: true
    src: /tmp/{{ daemon }}
    dest: '{{ user_dir }}/go/bin/{{ daemon }}'
    mode: '0755'
