---
# need to redo config.toml to ensure it is correct
network: celestia
folder: '.celestia-app'
daemon: celestia-appd
chain_id: mocha-4
node_version: 'v1.0.0-rc16'
repo: https://github.com/celestiaorg/celestia-app.git
genesis: 'https://raw.githubusercontent.com/celestiaorg/networks/master/mocha-4/genesis.json'
seeds: '3314051954fc072a0678ec0cbac690ad8676ab98@65.108.66.220:26656'
peers: '3314051954fc072a0678ec0cbac690ad8676ab98@65.108.66.220:26656,258f523c96efde50d5fe0a9faeea8a3e83be22ca@seed.mocha-4.celestia.aviaone.com:20279,3f472746f46493309650e5a033076689996c8881@celestia-tvagrnaestnet.rpc.kjnodes.com:20659'
custom_port_prefix: 116
update_website_immediately: true

# [Optional] Snapshot
snapshot_hour: 2
snapshot_minute: 0
